### ISSUE TITLE
Create Ticket Component

### ISSUE THREAD

**Issue by SheW0lf** [SheW0lf/Tikit#2]
## Description
Create the ticket component that will eventually house the issue data from Github

## Tasks

- Finish building the ticket component in `client/src/components/Ticket.tsx`  utilizing the `Ticket` interface to build the necessary elements to display the data. 
- Render a completed `Ticket` component within one or more of the ticket columns
- utilize Tailwind.css for the styling

**Comment by Tshamp7** [comment]
I would like this issue please!
